---
title: "CoMMA sample workflow"
format: html
---

## Example script for using CoMMA

### Loading data

```{r load_libraries}
library(tidyverse)
library(plyranges)
library(SummarizedExperiment)
#library(CoMMA)
```

```{r input_methylation_data}
# Samples will be named according to their names in this list
paths <- list(wt1 = "./data-raw/wt1_mg.bed",
              wt2 = "./data-raw/wt2_mg.bed",
              wt3 = "./data-raw/wt3_mg.bed")

# This can be a path to a GFF file
gff_path <- "./ncbi_dataset/ncbi_dataset/data/GCF_000005845.2/genomic.gff"

# Or you can read in an alternate annotation into a GRanges object
annotation <- read.delim("./data-raw/all_site_annotations.txt", sep = "\t", header = TRUE) |> 
  dplyr::select(-6)
colnames(annotation) <- c("name", "type", "left", "right", "strand")
annotation[is.na(annotation$strand), "strand"] <- "*"
annotation$seqnames <- "NC_000913.3"
annotation$start <- pmin(annotation$left, annotation$right)
annotation$end <- pmax(annotation$left, annotation$right)
annotation <- annotation[, c("seqnames", "start", "end", "strand", "width", "type", "name")]

annotation <- annotation |> 
  as_granges()

dat <- buildMicrobeMethyl(paths, annotation)

dat <- mmBtoM(dat)

dat <- dat |> 
  mmFilter(type == "IS-Elements" | type == "Genes")



```


