#' Synthetic example methylation dataset for the comma package
#'
#' A \code{\link{commaData}} object built from simulated Oxford Nanopore
#' methylation data. This dataset is used in package examples, vignettes, and
#' tests. It does not represent real biological data.
#'
#' @format A \code{commaData} object with:
#' \describe{
#'   \item{\strong{Sites}}{300 methylation sites (200 × 6mA, 100 × 5mC) on a
#'     simulated 100 kb chromosome (\code{"chr_sim"}).}
#'   \item{\strong{Samples}}{3 samples: \code{ctrl_1} and \code{ctrl_2}
#'     (condition \code{"control"}) and \code{treat_1}
#'     (condition \code{"treatment"}).}
#'   \item{\strong{Assays}}{
#'     \describe{
#'       \item{\code{methylation}}{Beta values (proportion methylated reads,
#'         0–1). \code{NA} where coverage < 5.}
#'       \item{\code{coverage}}{Integer read depth (10–50 per site).}
#'     }
#'   }
#'   \item{\strong{rowData}}{Per-site metadata including \code{chrom},
#'     \code{position}, \code{strand}, \code{mod_type}, \code{motif}
#'     (\code{"GATC"} for 6mA sites, \code{"CCWGG"} for 5mC sites), and
#'     \code{is_diff} (ground-truth differential methylation status for
#'     testing purposes).}
#'   \item{\strong{colData}}{Per-sample metadata: \code{sample_name},
#'     \code{condition}, \code{replicate}, \code{caller}.}
#'   \item{\strong{genomeInfo}}{Named integer vector: \code{c(chr_sim = 100000L)}.}
#'   \item{\strong{annotation}}{5 simulated genomic features (genes, rRNA, tRNA).}
#'   \item{\strong{motifSites}}{Empty \code{GRanges} (no motif search was run).}
#' }
#'
#' @details
#' The dataset simulates an experiment where ~30 of the 200 6mA sites are
#' differentially methylated between control and treatment conditions. Control
#' samples have high methylation at these sites (~0.9 beta), while the
#' treatment sample has low methylation (~0.25 beta). This ground truth is
#' stored in \code{rowData(comma_example_data)$is_diff} for use in testing
#' \code{diffMethyl()} (implemented in Phase 4).
#'
#' 5mC sites are not differentially methylated and serve to test multi-
#' modification-type functionality.
#'
#' The dataset was generated by \code{data-raw/create_example_data.R} using
#' \code{set.seed(1312)}.
#'
#' @examples
#' data(comma_example_data)
#' comma_example_data
#' modTypes(comma_example_data)
#' motifs(comma_example_data)
#' sampleInfo(comma_example_data)
#' dim(methylation(comma_example_data))
#'
#' @return A \code{\link{commaData}} object (see Details and Format sections
#'   above for structure).
#'
#' @source Simulated data generated by \code{data-raw/create_example_data.R}
#'
#' @name comma_example_data
#' @docType data
#' @keywords datasets
NULL
